import { Shield, ExternalLink } from 'lucide-react';

export function PdfFooter() {
  return (
    <div className="pdf-footer hidden print:block mt-8 pt-6 border-t border-slate-200">
      <div className="flex items-center justify-between text-sm text-slate-500">
        <div className="flex items-center gap-2">
          <Shield className="w-4 h-4 text-emerald-500" />
          <span>Generated by RemodelerIQ</span>
        </div>
        <div className="flex items-center gap-1">
          <ExternalLink className="w-3 h-3" />
          <span>remodeleriq.com</span>
        </div>
      </div>
      <p className="mt-2 text-xs text-slate-400">
        This report is for informational purposes only. Pricing benchmarks are estimates based on regional data and may vary. 
        Always verify contractor credentials independently before signing any contracts.
      </p>
    </div>
  );
}
